services:
  rabbitmq1:
    image: rabbitmq:3.10.7-management-alpine
    hostname: rabbitmq-vm-1
    # domainname: rabbitmq.lab
    extra_hosts:
    - rabbitmq1.rabbitmq.lab:10.5.0.11
    - rabbitmq2.rabbitmq.lab:10.5.0.12
    - rabbitmq3.rabbitmq.lab:10.5.0.13
    networks:
      rabbitmq:
        ipv4_address: 10.5.0.11
        aliases:
        - rabbitmq1.rabbitmq.lab
    volumes:
    - type: bind
      source: ./certs
      target: /certs
    - type: bind
      source: ./config
      target: /etc/rabbitmq
    - type: bind
      target: /var/log/rabbitmq
      source: ./logs
    expose:
      - "5671"
      - "15671"
    ports:
      - "15671:15671"
      - "15672:15672"
    environment:
      - RABBITMQ_ERLANG_COOKIE=UQQphObWgrI7dzYr7P6D
      - RABBITMQ_DEFAULT_USER=lab
      - RABBITMQ_DEFAULT_PASS=rabbit123
      - RABBITMQ_NODENAME=rabbit@rabbitmq1.rabbitmq.lab
      - RABBITMQ_USE_LONGNAME=true

  rabbitmq2:
    image: rabbitmq:3.10.7-management-alpine
    hostname: rabbitmq-vm-2
    #domainname: rabbitmq.lab
    extra_hosts:
    - rabbitmq1.rabbitmq.lab:10.5.0.11
    - rabbitmq2.rabbitmq.lab:10.5.0.12
    - rabbitmq3.rabbitmq.lab:10.5.0.13
    networks:
      rabbitmq:
        ipv4_address: 10.5.0.12
        aliases:
        - rabbitmq2.rabbitmq.lab
    volumes:
    - type: bind
      source: ./certs
      target: /certs
    - type: bind
      source: ./config
      target: /etc/rabbitmq
    - type: bind
      target: /var/log/rabbitmq
      source: ./logs
    environment:
      - RABBITMQ_ERLANG_COOKIE=UQQphObWgrI7dzYr7P6D
      - RABBITMQ_DEFAULT_USER=lab
      - RABBITMQ_DEFAULT_PASS=rabbit123
      - RABBITMQ_NODENAME=rabbit@rabbitmq2.rabbitmq.lab
      - RABBITMQ_USE_LONGNAME=true
  rabbitmq3:
    image: rabbitmq:3.10.7-management-alpine
    hostname: rabbitmq-vm-3
    #domainname: rabbitmq.lab
    extra_hosts:
    - rabbitmq1.rabbitmq.lab:10.5.0.11
    - rabbitmq2.rabbitmq.lab:10.5.0.12
    - rabbitmq3.rabbitmq.lab:10.5.0.13
    networks:
      rabbitmq:
        ipv4_address: 10.5.0.13
        aliases:
        - rabbitmq3.rabbitmq.lab
    volumes:
    - type: bind
      source: ./certs
      target: /certs
    - type: bind
      source: ./config
      target: /etc/rabbitmq
    - type: bind
      target: /var/log/rabbitmq
      source: ./logs
    environment:
      - RABBITMQ_ERLANG_COOKIE=UQQphObWgrI7dzYr7P6D
      - RABBITMQ_DEFAULT_USER=lab
      - RABBITMQ_DEFAULT_PASS=rabbit123
      - RABBITMQ_NODENAME=rabbit@rabbitmq3.rabbitmq.lab
      - RABBITMQ_USE_LONGNAME=true
networks:
  rabbitmq:
    driver: bridge
    ipam:
      config:
      - subnet: 10.5.0.0/16
        gateway: 10.5.0.1